### ISSUE TITLE
unknown document label, e.g.,  (news,1)

### ISSUE THREAD

**Issue by Tracy2014** [myleott/JGibbLabeledLDA#2]
Thanks for sharing the Labelled LDA solution. I tried with [news,1 tech,2], it shows warning for the unknown label. looking at the code in LDADataSet:addDoc,

`try {
                        label_set.add(Integer.parseInt(labelStr));
                    } catch (NumberFormatException nfe) {
                        System.err.println("Unknown document label ( " + labelStr + " ) for document " + docs.size() + ".");
                    }`

I think the reason is that, 'Integer.parseInt(labelStr)' always fails for the label formate `label_1,int`.

**Comment by myleott** [comment]
I think you may be using the wrong label format. It should just be space-separated ints, surrounded by square brackets, e.g.:

  [1 2]

The splitting on spaces happens above the code you referenced.
