### ISSUE TITLE
Problem compiling source

### ISSUE THREAD

**Issue by enewe101** [myleott/JGibbLabeledLDA#7]
Hi there,

I'm trying to use your code, but running into problems.  After cloning the repo, I try to compile the code, but it issues errors.  When I do:

    $ javac -cp lib/args4j-2.0.6.jar:lib/trove-3.0.3.jar src/jgibblda/Estimator.java

I get 

    src/jgibblda/Estimator.java:37: error: cannot find symbol
        protected Model trnModel;
                  ^
      symbol:   class Model
      location: class Estimator
    src/jgibblda/Estimator.java:38: error: cannot find symbol
        LDACmdOption option;
        ^
      symbol:   class LDACmdOption
      location: class Estimator
    src/jgibblda/Estimator.java:40: error: cannot find symbol
        public Estimator(LDACmdOption option) throws FileNotFoundException, IOException
                         ^
      symbol:   class LDACmdOption
      location: class Estimator
    src/jgibblda/Estimator.java:44: error: cannot find symbol
            trnModel = new Model(option);
                           ^
      symbol:   class Model
      location: class Estimator
    src/jgibblda/Estimator.java:46: error: illegal start of type
            if (option.est){
               ^
    src/jgibblda/Estimator.java:49: error: illegal start of type
            else if (option.estc){
                    ^
    6 errors

I rarely use java, but my instinct tells me this is because of the code being written for a different versio of Java.  I'm using 1.8.0_131.  What is the intended version, or, how do I solve this.  Thanks in advance!

**Comment by myleott** [comment]
I haven't used this code myself in a few years and also don't write much Java anymore :) But my feeling is this is actually a classpath issue. Try adding `src/jgibblda` to your `-cp` argument.

**Comment by enewe101** [comment]
Thanks @myleott .

Wow took me awhile to figure it out.  The answer is to put the *parent* of the package directory in the class path, which in this case is `src`

Sitting in the cloned directory (`JGibbLabeledLDA`) this works:

    javac -cp lib/args4j-2.0.6.jar:lib/trove-3.0.3.jar:src src/jgibblda/Model.java

Probably obvious to routine Java users!
